source 'https://rubygems.org'
gem 'asciidoctor', '1.5.8'
gem 'asciidoctor-diagram', '~> 1.4.0'
gem 'asciidoctor-pdf'
gem 'tilt'
gem 'thread_safe'
gem 'slim'  # for dzslides Slides
gem 'haml'  # for deckjs Slides
gem 'pygments.rb'
gem 'concurrent-ruby'
