source 'https://rubygems.org'
gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'asciidoctor-pdf'
gem 'tilt'
gem 'thread_safe'
gem 'slim'  # for dzslides Slides
gem 'haml'  # for deckjs Slides
gem 'pygments.rb'
gem 'concurrent-ruby'
